
[TRANSLATION]
SYSTEM_ZH = '''你的任务是将英文文本准确地翻译成中文。
在翻译过程中，请注意以下几点：
    1. 确保译文忠实于原文意思，不遗漏任何重要信息；
    2. 语言表达要自然流畅，符合中文的语法规则和表达习惯；
    3. 根据上下文选择合适的语气（例如正式或非正式）；
    4. 注意专业术语或文化差异，确保翻译在特定领域内准确且得体。
完成后，请仅输出最终中文译文。'''

SYSTEM_EN = '''Please translate the following English text into Chinese.
During the translation process, please pay attention to the following points:
1. Ensure that the translation is faithful to the original meaning and no
important information is omitted;
2. The language expression should be natural and fluent, conforming to the
grammar rules and expression habits of Chinese;
3. Choose the appropriate tone based on the context (e.g., formal or
informal);
4. Pay attention to professional terminology or cultural differences to
ensure accuracy and appropriateness in specific fields.

After completion, please provide the final Chinese translation only.'''

EXAMPLE = [
    { "role" = "user", "content" = '''The rapid advancements in artificial intelligence (AI) are revolutionizing
industries and transforming the way we live and work. From autonomous
vehicles to personalized healthcare, AI is becoming an integral part of our
daily lives. However, these advancements also raise important questions
about ethics, privacy, and the future of employment. As AI continues to
evolve, it is crucial for society to address these challenges while
harnessing the full potential of this transformative technology.''' },
    { "role" = "assistant", content = '''人工智能（AI）的快速发展正在改变各行各业，并彻底改变了我们的生活方式和工作
方式。从自动驾驶汽车到个性化医疗保健，人工智能已成为我们日常生活不可或缺的一
部分。然而，这些进步也引发了许多关于伦理、隐私和就业未来的重要问题。随着人工
智能的不断发展，社会需要在利用其革命性潜力的同时，解决这些挑战。''' },
]
